const preferredSourceMeta = {
  preferred_x: {
    priorityTier: "preferred_x",
    preferred: true,
    noisePenalty: 0,
    topicBoosts: { model: 8, product: 8, opinion: 6, education: 5, culture: 5 },
  },
  official_first_party: {
    priorityTier: "official_first_party",
    preferred: true,
    noisePenalty: 0,
    topicBoosts: { model: 10, product: 10, research: 6 },
  },
  expert_rss: {
    priorityTier: "expert_rss",
    preferred: true,
    noisePenalty: 0,
    topicBoosts: { opinion: 9, research: 6, product: 4 },
  },
  cn_media: {
    priorityTier: "cn_media",
    preferred: false,
    noisePenalty: 4,
    topicBoosts: { industry: 5, product: 4, education: 4, culture: 4 },
  },
  community_fallback: {
    priorityTier: "community_fallback",
    preferred: false,
    noisePenalty: 14,
    topicBoosts: { research: 4, opensource: 4, education: 3, culture: 3 },
  },
  reference: {
    priorityTier: "reference",
    preferred: true,
    noisePenalty: 0,
    topicBoosts: { model: 6, product: 6, opinion: 4 },
  },
};

function withMeta(source, priorityTier) {
  return {
    ...preferredSourceMeta[priorityTier],
    ...source,
    priorityTier,
  };
}

const DEFAULT_SOURCES = [
  withMeta({
    id: "aihot-public",
    name: "AIHOT 公开页",
    kind: "aihot",
    url: "https://aihot.virxact.com/",
    enabled: true,
    tier: "reference",
    timeoutMs: 12000,
    retries: 0,
  }, "reference"),
  withMeta({
    id: "x-aihot-bridge",
    name: "X 高价值聚合线索",
    kind: "x_reference",
    url: "https://aihot.virxact.com/",
    enabled: true,
    tier: "social",
    limit: 40,
    timeoutMs: 12000,
    retries: 0,
  }, "preferred_x"),
  withMeta({
    id: "ithome-ai-rss",
    name: "IT之家 AI",
    kind: "rss",
    url: "https://www.ithome.com/rss/",
    enabled: true,
    tier: "cn_media",
    limit: 40,
  }, "cn_media"),
  withMeta({
    id: "ifanr-rss",
    name: "爱范儿",
    kind: "rss",
    url: "https://www.ifanr.com/feed",
    enabled: true,
    tier: "cn_media",
    limit: 30,
  }, "cn_media"),
  withMeta({
    id: "geekpark-rss",
    name: "极客公园",
    kind: "rss",
    url: "https://www.geekpark.net/rss",
    enabled: true,
    tier: "cn_media",
    limit: 30,
  }, "cn_media"),
  withMeta({
    id: "qbitai-rss",
    name: "量子位",
    kind: "rss",
    url: "https://www.qbitai.com/feed",
    enabled: true,
    tier: "cn_media",
    limit: 30,
  }, "cn_media"),
  withMeta({
    id: "openai-news",
    name: "OpenAI News",
    kind: "rss",
    url: "https://openai.com/news/rss.xml",
    enabled: true,
    tier: "first_party",
    limit: 40,
  }, "official_first_party"),
  withMeta({
    id: "anthropic-news",
    name: "Anthropic News",
    kind: "web_list",
    url: "https://www.anthropic.com/news",
    enabled: true,
    tier: "first_party",
  }, "official_first_party"),
  withMeta({
    id: "anthropic-research",
    name: "Anthropic Research",
    kind: "web_list",
    url: "https://www.anthropic.com/research",
    enabled: true,
    tier: "first_party",
  }, "official_first_party"),
  withMeta({
    id: "google-ai-blog",
    name: "Google AI Blog",
    kind: "rss",
    url: "https://blog.google/technology/ai/rss/",
    enabled: true,
    tier: "first_party",
    limit: 30,
  }, "official_first_party"),
  withMeta({
    id: "deepmind-blog",
    name: "Google DeepMind",
    kind: "rss",
    url: "https://deepmind.google/discover/blog/rss.xml",
    enabled: true,
    tier: "first_party",
    limit: 30,
  }, "official_first_party"),
  withMeta({
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    kind: "rss",
    url: "https://huggingface.co/blog/feed.xml",
    enabled: true,
    tier: "first_party",
    limit: 30,
  }, "official_first_party"),
  withMeta({
    id: "nvidia-ai-blog",
    name: "NVIDIA AI Blog",
    kind: "rss",
    url: "https://blogs.nvidia.com/blog/category/enterprise/deep-learning/feed/",
    enabled: true,
    tier: "first_party",
    limit: 30,
  }, "official_first_party"),
  withMeta({
    id: "cloudflare-ai",
    name: "Cloudflare AI",
    kind: "rss",
    url: "https://blog.cloudflare.com/tag/ai/rss/",
    enabled: true,
    tier: "first_party",
    limit: 30,
  }, "official_first_party"),
  withMeta({
    id: "simon-willison",
    name: "Simon Willison",
    kind: "rss",
    url: "https://simonwillison.net/atom/everything/",
    enabled: true,
    tier: "expert",
    limit: 30,
  }, "expert_rss"),
  withMeta({
    id: "interconnects-ai",
    name: "Interconnects",
    kind: "rss",
    url: "https://www.interconnects.ai/feed",
    enabled: true,
    tier: "expert",
    limit: 25,
  }, "expert_rss"),
  withMeta({
    id: "dwarkesh-podcast",
    name: "Dwarkesh Podcast",
    kind: "rss",
    url: "https://www.dwarkeshpatel.com/feed",
    enabled: true,
    tier: "expert",
    limit: 20,
  }, "expert_rss"),
  withMeta({
    id: "tomer-tunguz",
    name: "Tomer Tunguz",
    kind: "rss",
    url: "https://tomtunguz.com/index.xml",
    enabled: true,
    tier: "expert",
    limit: 20,
  }, "expert_rss"),
  withMeta({
    id: "gary-marcus",
    name: "Gary Marcus",
    kind: "rss",
    url: "https://garymarcus.substack.com/feed",
    enabled: true,
    tier: "expert",
    limit: 20,
  }, "expert_rss"),
  withMeta({
    id: "xai-news",
    name: "xAI News",
    kind: "web_list",
    url: "https://x.ai/news",
    enabled: true,
    tier: "first_party",
    limit: 12,
  }, "official_first_party"),
  withMeta({
    id: "claude-code-releases",
    name: "Claude Code Releases",
    kind: "rss",
    url: "https://github.com/anthropics/claude-code/releases.atom",
    enabled: true,
    tier: "first_party",
    limit: 20,
  }, "official_first_party"),
  withMeta({
    id: "github-blog-ai",
    name: "GitHub Blog AI",
    kind: "rss",
    url: "https://github.blog/ai-and-ml/feed/",
    enabled: true,
    tier: "first_party",
    limit: 25,
  }, "official_first_party"),
  withMeta({
    id: "github-changelog",
    name: "GitHub Changelog",
    kind: "rss",
    url: "https://github.blog/changelog/feed/",
    enabled: true,
    tier: "first_party",
    limit: 25,
  }, "official_first_party"),
  withMeta({
    id: "apple-ml-research",
    name: "Apple Machine Learning Research",
    kind: "rss",
    url: "https://machinelearning.apple.com/rss.xml",
    enabled: true,
    tier: "first_party",
    limit: 25,
  }, "official_first_party"),
  withMeta({
    id: "openrouter-announcements",
    name: "OpenRouter Announcements",
    kind: "rss",
    url: "https://openrouter.ai/announcements/rss.xml",
    enabled: true,
    tier: "first_party",
    limit: 25,
  }, "official_first_party"),
  withMeta({
    id: "bair-blog",
    name: "BAIR Berkeley AI Research",
    kind: "rss",
    url: "https://bair.berkeley.edu/blog/feed.xml",
    enabled: true,
    tier: "research",
    limit: 25,
  }, "expert_rss"),
  withMeta({
    id: "cursor-blog",
    name: "Cursor Blog",
    kind: "web_list",
    url: "https://www.cursor.com/blog",
    enabled: true,
    tier: "first_party",
    limit: 12,
  }, "official_first_party"),
  withMeta({
    id: "runway-news",
    name: "Runway News",
    kind: "web_list",
    url: "https://runwayml.com/news",
    enabled: true,
    tier: "culture",
    limit: 12,
  }, "official_first_party"),
  withMeta({
    id: "hn-ai",
    name: "Hacker News AI",
    kind: "hn",
    url: "https://hn.algolia.com/api/v1/search_by_date?query=AI%20OR%20LLM%20OR%20OpenAI%20OR%20Claude%20OR%20agent&tags=story&hitsPerPage=12",
    enabled: true,
    tier: "community",
  }, "community_fallback"),
  withMeta({
    id: "hn-ai-education",
    name: "Hacker News AI Education",
    kind: "hn",
    url: "https://hn.algolia.com/api/v1/search_by_date?query=AI%20education%20OR%20AI%20tutor%20OR%20LLM%20education&tags=story&hitsPerPage=8",
    enabled: true,
    tier: "education",
  }, "community_fallback"),
  withMeta({
    id: "hn-ai-culture",
    name: "Hacker News AI Culture",
    kind: "hn",
    url: "https://hn.algolia.com/api/v1/search_by_date?query=AI%20art%20OR%20generative%20art%20OR%20AI%20copyright&tags=story&hitsPerPage=8",
    enabled: true,
    tier: "culture",
  }, "community_fallback"),
  withMeta({
    id: "github-ai",
    name: "GitHub AI Trending",
    kind: "github",
    url: "https://api.github.com/search/repositories?q=topic:artificial-intelligence+stars:%3E5000&sort=updated&order=desc&per_page=10",
    enabled: true,
    tier: "community",
  }, "community_fallback"),
  withMeta({
    id: "github-ai-education",
    name: "GitHub AI Education",
    kind: "github",
    url: "https://api.github.com/search/repositories?q=artificial-intelligence+education+stars:%3E500&sort=updated&order=desc&per_page=8",
    enabled: true,
    tier: "education",
  }, "community_fallback"),
  withMeta({
    id: "github-ai-culture",
    name: "GitHub AI Culture",
    kind: "github",
    url: "https://api.github.com/search/repositories?q=artificial-intelligence+generative-art+stars:%3E500&sort=updated&order=desc&per_page=8",
    enabled: true,
    tier: "culture",
  }, "community_fallback"),
  withMeta({
    id: "arxiv-ai",
    name: "arXiv AI",
    kind: "arxiv",
    url: "https://export.arxiv.org/api/query?search_query=cat:cs.AI+OR+cat:cs.CL+OR+cat:cs.LG&start=0&max_results=20&sortBy=submittedDate&sortOrder=descending",
    enabled: true,
    tier: "research",
  }, "community_fallback"),
  withMeta({
    id: "arxiv-ai-education",
    name: "arXiv AI Education",
    kind: "arxiv",
    url: "https://export.arxiv.org/api/query?search_query=all:%22AI%20education%22+OR+all:edtech+OR+all:tutoring&start=0&max_results=20&sortBy=submittedDate&sortOrder=descending",
    enabled: true,
    tier: "education",
  }, "community_fallback"),
  withMeta({
    id: "arxiv-ai-culture",
    name: "arXiv AI Culture",
    kind: "arxiv",
    url: "https://export.arxiv.org/api/query?search_query=all:%22AI%20art%22+OR+all:%22generative%20art%22+OR+all:%22AI%20music%22&start=0&max_results=20&sortBy=submittedDate&sortOrder=descending",
    enabled: true,
    tier: "culture",
  }, "community_fallback"),
  withMeta({
    id: "devto-ai",
    name: "Dev.to AI",
    kind: "devto",
    url: "https://dev.to/api/articles?tag=ai&per_page=8",
    enabled: false,
    deprecated: true,
    tier: "community",
  }, "community_fallback"),
  withMeta({
    id: "devto-ai-education",
    name: "Dev.to AI Education",
    kind: "devto",
    url: "https://dev.to/api/articles?tag=ai&per_page=8&tag=education",
    enabled: false,
    deprecated: true,
    tier: "education",
  }, "community_fallback"),
  withMeta({
    id: "devto-ai-culture",
    name: "Dev.to AI Culture",
    kind: "devto",
    url: "https://dev.to/api/articles?tag=ai&per_page=8&tag=art",
    enabled: false,
    deprecated: true,
    tier: "culture",
  }, "community_fallback"),
  withMeta({
    id: "x-ai-leaders",
    name: "X AI Leaders",
    kind: "x_profiles",
    url: "https://twiiit.com/{handle}/rss",
    mirrors: [
      "https://twiiit.com/{handle}/rss",
      "https://nitter.net/{handle}/rss",
      "https://xcancel.com/{handle}/rss",
      "https://rsshub.app/twitter/user/{handle}/excludeReplies=1",
    ],
    handles: [
      "OpenAI",
      "AnthropicAI",
      "GoogleDeepMind",
      "huggingface",
      "sama",
      "karpathy",
      "AndrewYNg",
      "emollick",
      "drjimfan",
      "ylecun",
      "op7418",
      "guizang_ai",
      "BerriAI",
      "rohanpaul_ai",
      "swyx",
      "latentspacepod",
      "OpenRouterAI",
      "cursor_ai",
      "runwayml",
      "midjourney",
      "GoogleAI",
      "NVIDIAAI",
      "OpenAIDevs",
      "Kimmonismus",
      "AntBailing",
      "baoyu_io",
      "cb_doge",
      "PixVerseAI",
      "dair_ai",
      "tibo_maker",
      "pmarca",
      "oran_ge",
      "semiAnalysis_",
      "vista8",
      "GregBrockman",
    ],
    enabled: true,
    tier: "social",
    limit: 60,
    maxAttempts: 14,
    timeoutMs: 22000,
    retries: 0,
  }, "preferred_x"),
  withMeta({
    id: "mit-ai-rss",
    name: "MIT Technology Review AI",
    kind: "rss",
    url: "https://www.technologyreview.com/topic/artificial-intelligence/feed/",
    enabled: true,
    tier: "media",
    limit: 30,
  }, "expert_rss"),
];

function mergeDefaultSources(existing = []) {
  const byId = new Map(existing.map((source) => [source.id, source]));
  for (const source of DEFAULT_SOURCES) {
    const current = byId.get(source.id);
    byId.set(source.id, {
      ...source,
      enabled: source.deprecated ? false : current?.enabled ?? source.enabled,
      health: current?.health || null,
    });
  }
  return [...byId.values()];
}

module.exports = {
  DEFAULT_SOURCES,
  mergeDefaultSources,
};
