import { useState, type FormEvent } from "react";
import { data, useLoaderData, useRevalidator } from "react-router";
import { adminGet } from "../../lib/admin.server";
import { buttonClass } from "../../components/ui/Controls";
interface Item {id:string;title:string;sourceName:string;score:number;hidden:boolean;pinned:boolean;publishedAt:string|null}
interface Source {id:string;name:string;kind:string;url:string;enabled:boolean;priorityTier:string;health:{ok?:boolean;error?:string}|null}
interface Feedback {id:string;message:string;contact:string;page:string;status:string;createdAt:string;screenshot?:string}
interface Mp {id:string;title:string;url:string;account:string;score:number}
interface State {items:Item[];sources:Source[];feedback:Feedback[];runs:Array<{at:string;added?:number;total?:number;error?:string}>;mpArticles:Mp[];settings:{cron:string;rules:{selectedThreshold:number}};dailyCount:number}
const labels:Record<string,string>={home:"概览",content:"内容",sources:"信源",mp:"公众号",feedback:"反馈",runs:"运行记录",settings:"设置"};
export async function loader({request,params}:{request:Request;params:Record<string,string|undefined>}){
 const section=params.section||"home";if(!labels[section])throw data({message:"not_found"},{status:404});
 return {section,state:await adminGet<State>(request,"/api/admin/site-state")};
}
const field="h-10 w-full rounded-control border border-line-strong bg-surface px-3 text-sm text-ink";
function Entry({label,children}:{label:string;children:React.ReactNode}){return <label className="block space-y-2 text-[13px] text-ink-3"><span>{label}</span>{children}</label>}
export default function Manage(){
 const {section,state}=useLoaderData<typeof loader>();const revalidator=useRevalidator();const [query,setQuery]=useState("");const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
 async function command(path:string,method="POST",body?:unknown){setBusy(true);setStatus("正在处理…");try{const response=await fetch(path,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error||result.detail||"操作失败");setStatus("已完成");revalidator.revalidate();}catch(error){setStatus(error instanceof Error?error.message:"操作失败，请重试");}finally{setBusy(false)}}
 function submit(event:FormEvent<HTMLFormElement>,path:string,method="POST"){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));void command(path,method,values)}
 const action=(label:string,fn:()=>void)=><button disabled={busy} className={buttonClass("secondary","md")} onClick={fn}>{label}</button>;
 return <div className="mx-auto max-w-[1200px] space-y-6 p-5 lg:p-8">
  <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs tracking-widest text-accent">AI.BAIZE</p><h1 className="mt-2 text-3xl font-black text-ink">{labels[section]}</h1></div><p role="status" className="text-sm text-ink-3">{status}</p></header>
  {section==="home"&&<><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[["内容",state.items.length],["信源",state.sources.length],["待处理反馈",state.feedback.filter(f=>f.status==="open").length],["已存日报",state.dailyCount]].map(([label,count])=><div key={label} className="card p-5"><p className="text-sm text-ink-3">{label}</p><p className="num mt-3 text-3xl font-bold text-ink">{count}</p></div>)}</div><section className="card space-y-4 p-5"><h2 className="font-semibold text-ink">内容更新</h2><p className="text-sm text-ink-3">采集与日报继续使用本站现有服务。结果可在运行记录中查看。</p><div className="flex flex-wrap gap-3">{action("立即采集",()=>void command("/api/admin/refresh"))}{action("生成日报",()=>void command("/api/admin/daily"))}{action("整理最近内容",()=>void command("/api/admin/enhance","POST",{limit:60}))}</div></section></>}
  {(section==="content"||section==="sources")&&<input className={`${field} max-w-md`} aria-label="搜索" placeholder="搜索名称或标题" value={query} onChange={e=>setQuery(e.target.value)}/>}
  {section==="content"&&<div className="space-y-2">{state.items.filter(i=>`${i.title} ${i.sourceName}`.toLowerCase().includes(query.toLowerCase())).slice(0,200).map(i=><article key={i.id} className="card flex flex-wrap items-center justify-between gap-4 p-4"><div className="min-w-0 flex-1"><a href={`/items/${i.id}`} className="font-semibold text-ink hover:text-accent">{i.title}</a><p className="mt-2 text-xs text-ink-4">{i.sourceName} · 评分 {i.score} · {i.hidden?"已隐藏":"可见"}{i.pinned?" · 已置顶":""}</p></div><div className="flex gap-2">{action(i.hidden?"恢复展示":"隐藏",()=>void command(`/api/admin/items/${encodeURIComponent(i.id)}`,"PUT",{hidden:!i.hidden}))}{action(i.pinned?"取消置顶":"置顶",()=>void command(`/api/admin/items/${encodeURIComponent(i.id)}`,"PUT",{pinned:!i.pinned}))}</div></article>)}<p className="text-xs text-ink-4">本页最多展示 200 条，请用搜索缩小范围。</p></div>}
  {section==="sources"&&<><form className="card grid gap-4 p-5 md:grid-cols-2" onSubmit={e=>submit(e,"/api/admin/sources")}><Entry label="信源名称"><input name="name" required className={field}/></Entry><Entry label="地址"><input name="url" type="url" required className={field}/></Entry><Entry label="类型"><select name="kind" className={field}><option value="rss">RSS</option><option value="web_list">网页列表</option><option value="x_profiles">X 账号</option></select></Entry><Entry label="来源分类"><select name="priorityTier" className={field}><option value="custom">其他来源</option><option value="official_first_party">官方一手</option><option value="cn_media">中文媒体</option></select></Entry><button disabled={busy} className={buttonClass("primary","md")}>添加信源</button></form><div className="space-y-2">{state.sources.filter(s=>`${s.name} ${s.url}`.toLowerCase().includes(query.toLowerCase())).map(s=><article key={s.id} className="card flex flex-wrap items-center justify-between gap-3 p-4"><div className="min-w-0"><h2 className="font-semibold text-ink">{s.name}</h2><p className="mt-1 max-w-xl truncate text-xs text-ink-4">{s.kind} · {s.enabled?"已启用":"已停用"} · {s.url}</p>{s.health?.error&&<p className="mt-1 text-xs text-hot">{s.health.error}</p>}</div>{action(s.enabled?"停用":"启用",()=>void command(`/api/admin/sources/${encodeURIComponent(s.id)}`,"PUT",{enabled:!s.enabled}))}</article>)}</div></>}
  {section==="feedback"&&<div className="space-y-3">{state.feedback.length===0&&<p className="text-sm text-ink-3">暂无反馈。</p>}{state.feedback.map(f=><article key={f.id} className="card space-y-3 p-5"><p className="whitespace-pre-wrap text-ink">{f.message}</p><p className="break-all text-xs text-ink-4">{f.createdAt} · {f.contact||"未留联系方式"} · {f.page}</p>{f.screenshot&&<a className="text-sm text-accent" href={`/api/admin/feedback/${encodeURIComponent(f.id)}/screenshot`} target="_blank" rel="noreferrer">查看截图</a>}{action(f.status==="open"?"标记已处理":"重新打开",()=>void command(`/api/admin/feedback/${encodeURIComponent(f.id)}`,"PUT",{status:f.status==="open"?"closed":"open"}))}</article>)}</div>}
  {section==="runs"&&<div className="space-y-2">{state.runs.length===0&&<p className="text-sm text-ink-3">暂无运行记录。</p>}{state.runs.map((r,n)=><article key={`${r.at}-${n}`} className="card p-4"><time className="num text-sm text-ink">{r.at}</time><p className="mt-2 text-sm text-ink-3">新增 {r.added??"未记录"} · 合计 {r.total??"未记录"}</p>{r.error&&<p className="mt-2 text-sm text-hot">{r.error}</p>}</article>)}</div>}
  {section==="mp"&&<><form className="card grid gap-4 p-5 md:grid-cols-2" onSubmit={e=>submit(e,"/api/admin/mp/articles")}><Entry label="文章标题"><input name="title" required className={field}/></Entry><Entry label="原文地址"><input name="url" required type="url" className={field}/></Entry><Entry label="公众号"><input name="account" required className={field}/></Entry><Entry label="摘要"><input name="summary" className={field}/></Entry><button disabled={busy} className={buttonClass("primary","md")}>收录文章</button></form><div className="space-y-2">{state.mpArticles.map(i=><article key={i.id} className="card p-4"><a className="font-semibold text-ink hover:text-accent" href={i.url} target="_blank" rel="noreferrer">{i.title}</a><p className="mt-2 text-xs text-ink-4">{i.account} · 评分 {i.score}</p></article>)}</div></>}
  {section==="settings"&&<form className="card max-w-xl space-y-5 p-5" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void command("/api/admin/settings","PUT",{cron:form.get("cron"),rules:{selectedThreshold:Number(form.get("threshold"))}})}}><Entry label="采集时间规则"><input name="cron" defaultValue={state.settings.cron} required className={field}/></Entry><p className="text-xs text-ink-4">例如 */30 * * * * 表示每 30 分钟。修改时间规则后需重启采集服务生效。</p><Entry label="精选最低评分"><input name="threshold" type="number" min="0" max="100" defaultValue={state.settings.rules.selectedThreshold} required className={field}/></Entry><button disabled={busy} className={buttonClass("primary","md")}>保存设置</button></form>}
 </div>;
}
